version: 1
disable_existing_loggers: False

formatters:
    standard:
        format: '%(asctime)s - %(levelname)-8s - %(name)s - %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: standard
        stream: ext://sys.stdout

    file:
        class: logging.FileHandler
        level: INFO
        formatter: standard
        filename: 'log.log'
        encoding: utf8
        mode: a

loggers:
    development:
        level: DEBUG
        handlers: [console]
        propagate: no


root:
    level: DEBUG
    handlers: [console, file]